services:
  ameryd:
    build: .
    container_name: ameryd
    restart: always
    ports:
      - "2021:2021"
    volumes:
      - /media/sh3ldr0id-hdd/Ameryd:/app/data
    environment:
      - PORT=2021
      - FLASK_ENV=production
